### ISSUE TITLE
Allow for reserve for the size of collections?

### ISSUE THREAD

**Issue by adamdddave** [key4hep/EDM4hep#197]
I'm new to EDM4hep so apologies if this question is not placed in the correct place. 

I was looking into the use of EDM4hep for a simulation event model, and what I see is that in our old EDM, we would reserve the size of a collection of MC particles for memory pre-allocation. I don't see similar functionality within the EDM4hep model. As this inherits from podio, I'm not sure if this is better placed there, but it might be nice to be able to pre-allocate memory, specifically if the number of MCParticles may already be known.

Thanks!

**Comment by tmadlener** [comment]
Given that vectors (have to) grow exponentially, I am not sure testing with one filling 80 GB of doubles is close to a "real world" use case. In this case it has to grow to this size only once, but in real world use cases, the re-allocations might happen inside a rather tight loop, where `reserve`-ing the size of the vector (if it is known) can result in quite some speedup (depending on how well the contained objects can be relocated to their new allocation), and is something that is usually recommended to do for easy performance gains. (Also just pre-allocating to a size of 100, will save you at least 6 re-allocations, if you add more then 64 elements).

Having said that, currently `reserve` doesn't really make sense for podio generated EDM collections, since as already said they are stored in a `std::deque` which can grow without re-allocating. However, it is possible that this changes, once we have tackled all the other (bigger) issues that are currently still on our list for podio v1.0

**Comment by adamdddave** [comment]
Thanks for the replies! The use case is trying to incorporate EDM4hep as the standard EDM within the Gaussino framework. The reason for the reservation is exactly the one highlighted above. I'll carry on with the event model move and see whether or not we can profile any other changes as we go. Thanks again for the explanation!
