### ISSUE TITLE
Add 4D vector object

### ISSUE THREAD

**Issue by osbornjd** [key4hep/EDM4hep#245]
It would be useful to have a generic 4 vector type for (for example) storing position+time information of a particle or object, such as a track vertex. This could also be generalized for use as a generic 4 vector class, for example representing a position + time or momentum + energy.

**Comment by kkauder** [comment]
I believe, relatedly, we'll also need a `edm4eic::CovDiag4f` object.

**Comment by osbornjd** [comment]
There aren't other covariance object in the `edm4hep` yaml file (they are all packed arrays), so I'm not sure if the explicit diagonal covariance objects are something we should just keep in edm4eic.

**Comment by kkauder** [comment]
Correct, I was too hasty. Thought this was a edm4eic issue

**Comment by tmadlener** [comment]
I think this is in general a good idea. I still have a few questions / comments for discussion.

Could this functionality be implemented as something that happens in memory? I.e. we would not necessarily need a dedicated component in the datamodel but rather a handwritten c++ class. The proposal in #248 is effectively mainly `ExtraCode` at the moment.

We already have some [utilities](https://github.com/key4hep/EDM4hep/blob/main/utils/include/edm4hep/utils/kinematics.h) for getting e.g. the 4 momenta from anything that has a `momentum` (and either a `mass` or `energy` but that is somewhat optional). This has the advantage that we immediately have something in our hands that supports all the 4-vector operations. These we would otherwise have to implement ourselves or provide some conversion functionality. This should be extensible to more datatypes that do not have a `momentum` directly but rather something that can be converted into one.

**Comment by osbornjd** [comment]
I am open to implementing this in some other way if you think it is best as I don't have deep knowledge of the edm4hep project, but my initial attempt was to basically model what was implemented for `Vector::3f`. The only reason that I think it would be useful to have a generic 4vector object is that you could in principle have something like `(px,py,pz,E)` or (eta,phi,M,E)` or `(x,y,z,t)` so some utility implementation would have to have the ability to be extensible to a generic range of data types that fit all of these possibilities (I think that is effectively what you said also). So this would have to foresee all use cases of 4-vector operations rather than handing the object to the user and having them do whatever they want with it.

**Comment by tmadlener** [comment]
The main question in the end is: Do we also want to persist these 4-vectors as sort of built-in edm4hep types or are we fine of constructing them only in memory. Because I would be in favor of having an existing implementation for the in-memory handling / representation. Currently the utilities use `ROOT::Math::PxPyPzEVector` / `ROOT::Math::PxPyPzMVector` depending on how you call `edm4hep::utils::p4`.

**Comment by osbornjd** [comment]
Okay, so if I understand correctly your suggestion is to just use the already existing utilities functions to get 4vector capabilities rather than having a built-in `Vector4` type?

**Comment by osbornjd** [comment]
Sure, let me discuss it within our EIC team and I will come back to this. In the meantime I will just leave the PR and issue open, and close them in the event we decide the objects in memory are sufficient.

**Comment by osbornjd** [comment]
For us (at least in the EIC context, but this would in principle be relevant for a wide variety of experiments) the 4 vector tools that we need are in the context of 4D track reconstruction and are really using classical 4D coordinates. For example, we need output objects that look like `(x,y,z,t)` for a vertexing algorithm. In principle someone could still interpret this as a general 4 vector and use it in memory, or could use the `edm4hep::utils` function to utilize these helpers without storing anything explicitly in memory. But in the context of 4D track reconstruction, it would make sense to have a component of the edm that keeps this information in the storage layer.

**Comment by tmadlener** [comment]
Ah alright. I think we might have talked about slightly different things then. I was mainly referring to the physics four vector (aka a Lorentz vector) with the usual invariants and attached operations. Whereas, IIUC, you were mainly after something that just has 4 floats with certain names (that match one representation of a typical four vector).

In that case I would have fewer concerns about adding this, provided we clearly document what the purpose of this type is (and maybe more importantly what it isn't).

**Comment by osbornjd** [comment]
> Whereas, IIUC, you were mainly after something that just has 4 floats with certain names (that match one representation of a typical four vector)

Exactly right, we need to have this as an actual storage object for our 4D tracking. Sorry for my miscommunication. Where do you suggest I add the proper the documentation in https://github.com/key4hep/EDM4hep/pull/248 ?

**Comment by tmadlener** [comment]
Yes. I would just put it into the `Description` of the `Vector4f` (I think I put that functionality into podio at some point). That will show up as the docstring of the generated c++ code.
