### ISSUE TITLE
Ninja regenerates datamodel sources during build

### ISSUE THREAD

**Issue by vvolkl** [key4hep/EDM4hep#49]
The CMake changes introduced in #48 work with Make, but ninja will regenerate the datamodel sources regardless of the timestamp of `edm4hep.yaml`. The build is still correct though, it is just one superfluous step.

**Comment by andresailer** [comment]
I now realize that the logic is insufficient, while the class_generator is re-run, it does this too late, after the objects are already compiled, because the dependency via selection.xml only affects the edm4hepDict.cxx file. If one adds all the `${headers}` and `${sources}` to the "OUTPUT" of the `add_custom_command`, then `make` will recompile all the objects. 
`Ninja` will not recompile all of them in this case, though.
